# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.


# NOTE: must set "Crossbow" as name to have the badge links working in the
# github comment reports!
name: Crossbow
on:
  push:
    branches:
      - "*-github-*"


jobs:
  test:
    name: |
      Docker Test  conan 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Arrow
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: arrow
          repository: mathworks/arrow
          ref: 0b90f2376f2e23127b237ac7db7da5bc09621179
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          cache: 'pip'
          python-version: 3.8
      - name: Install Archery
        shell: bash
        run: pip install -e arrow/dev/archery[all]


      - name: Execute Docker Build
        shell: bash
        run: |
          archery docker run \
            -e SETUPTOOLS_SCM_PRETEND_VERSION="8.0.0.dev1124" \
             \
            conan \
            

      - name: Dump R install logs
        if: always()
        run: |
          log=arrow/r/check/arrow.Rcheck/00install.out
          if [ -f ${log} ]; then
            cat ${log}
          fi
      - name: Dump R test logs
        if: always()
        run: |
          for log in arrow/r/check/arrow.Rcheck/tests/testthat.Rout*; do
            if [ -f ${log} ]; then
              echo ${log}
              cat ${log}
            fi
          done
      - name: Save the R test output
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-output
          path: arrow/r/check/arrow.Rcheck/tests/testthat.Rout*
          if-no-files-found: ignore
      - name: Print arrow.branch
        run: echo "arrow.branch = ARROW-15693"
      - name: Print arrow.head
        run: echo "arrow.head = 0b90f2376f2e23127b237ac7db7da5bc09621179"
      - name: Print arrow.remote
        run: echo "arrow.remote = https://github.com/mathworks/arrow.git"
      - name: Print arrow.email
        run: echo "arrow.email = fionala7@gmail.com"
      - name: Print arrow.default_branch
        run: echo "arrow.default_branch = ['main', 'master']"
      - name: Print macro, resolved here
        run: echo "macros.is_default_branch() = false"
      - name: Print macro, resolved previously
        run: echo "is_default_branch = false"
      - name: Directly check statement
        run: echo "arrow.branch in arrow.default_branch = False"

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image
        shell: bash
        run: archery docker push conan
